#include "MusicalScaleAbstract.h"
#include "MusicalScaleAbstract+.h"

@interface MusicalScaleBebopDominant:MusicalScaleAbstract @end
@interface MusicalScaleDiatonic:MusicalScaleAbstract @end
@interface MusicalScaleDiminished:MusicalScaleAbstract @end
@interface MusicalScaleHalfDiminished:MusicalScaleAbstract @end
@interface MusicalScaleWholeDiminished:MusicalScaleAbstract @end
@interface MusicalScaleWholeToneDiminished:MusicalScaleAbstract @end
@interface MusicalScaleDominant7th:MusicalScaleAbstract @end
@interface MusicalScaleDoubleHarmonic:MusicalScaleAbstract @end
@interface MusicalScaleHalfDiminishedLocrian:MusicalScaleAbstract @end
@interface MusicalScaleHalfDiminishedLocrian2:MusicalScaleAbstract @end
@interface MusicalScaleLeadingWholeTone:MusicalScaleAbstract @end
@interface MusicalScaleLydianAugmented:MusicalScaleAbstract @end
@interface MusicalScaleLydianMinor:MusicalScaleAbstract @end
@interface MusicalScaleLydianDiminished:MusicalScaleAbstract @end
@interface MusicalScaleMajorLocrian:MusicalScaleAbstract @end
@interface MusicalScaleMelodicMinorAscending:MusicalScaleAbstract @end
@interface MusicalScaleMelodicMinorDescending:MusicalScaleAbstract @end
@interface MusicalScaleEnigmatic:MusicalScaleAbstract @end
@interface MusicalScaleOctatonicHW:MusicalScaleAbstract @end
@interface MusicalScaleOctatonicWH:MusicalScaleAbstract @end
@interface MusicalScaleOvertone:MusicalScaleAbstract @end
@interface MusicalScaleOvertoneDominant:MusicalScaleAbstract @end
